# Generated by Django 3.2.16 on 2026-03-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Отметьте, чтобы пост отображался первым в ленте.', verbose_name='Закреплённый пост'),
        ),
    ]
