# Generated by Django 3.2.16 on 2026-03-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20260326_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, help_text='Расскажите немного о себе (до 256 символов)', max_length=256, verbose_name='О себе'),
        ),
    ]
